import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const wasmPath = resolve(root, "target/wasm32-unknown-unknown/release/tinyfft.wasm");

console.log("[1/3] cargo build --release --target wasm32-unknown-unknown");
execSync("cargo build --release --target wasm32-unknown-unknown", {
  cwd: root,
  stdio: "inherit",
});

console.log("[2/3] embed wasm bytes");
const wasm = readFileSync(wasmPath);
const b64 = wasm.toString("base64");
const out = `// Auto-generated by ts/build.mjs from target/wasm32-unknown-unknown/release/tinyfft.wasm. Do not edit.
export const WASM_BYTES_BASE64 = "${b64}";
`;
writeFileSync(resolve(here, "wasm-bytes.ts"), out);
console.log(`  wasm ${wasm.length} bytes -> base64 ${b64.length} chars`);

console.log("[3/3] tsc");
execSync("npx tsc", { cwd: root, stdio: "inherit" });

console.log("done");
